version: "3.9"

services:
  pocketbase:
    build: .
    container_name: edugame-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb/data
      - ./pb_public:/pb/pb_public
